### ISSUE TITLE
Cannot add Entity 'UpTime' on freshly installed v2024.1.1

### ISSUE THREAD

**Issue by Baxxy13** [richibrics/IoTuring#98]
While setting up IoTuring on a new system (debian bookworm), i cannot add the entity 'UpTime'.
It seems ignored.

Manually adding 'UpTime' to `configurations.json` works:

```json
    "active_entities": [
        {
            "type": "AppInfo"
        },
        {
            "type": "Uptime"
        },
        {
            "type": "BootTime"
        }
    ],
```

**Comment by richibrics** [comment]
Are the other entities shown correctly in the configuration menu ?

**Comment by Baxxy13** [comment]
Yes, i can add oll other entities without problems.
They then showed in entitity "overview".

Uptime won't add and won't showed in the overview.
![GIF 20 02 2024 18-05-13](https://github.com/richibrics/IoTuring/assets/54898249/44436a54-2670-4840-b9da-a089e98593eb)

**Comment by richibrics** [comment]
Thank you for the animation, you don't even get the New entity added message 🤔

**Comment by infeeeee** [comment]
I think the problem is the actual name and the `NAME` attribute of the Uptime class is different (`Uptime` vs `UpTime`). In all other classes it's the same.

We should check if the `NAME` attr is needed at all, the builtin `instance.__class__.__name__` or `type(instance).__name__` should return something similar, maybe that would be enough, so no similar bugs can happen in the future.

**Comment by Baxxy13** [comment]
Thx for fixing this.
It's working now (again) in 2024.6.1.
